1.procedimiento: 
. SELECT * FROM village
. SELECT * FROM INHABITANT 
. SELECT * FROM inhabitant WHERE job = 'butcher'
. SELECT * FROM INHABITANT WHERE state = 'friendly'
. SELECT * FROM INHABITANT WHERE state = 'friendly' AND job =
'weaponsmith'
. SELECT * FROM INHABITANT WHERE state = 'friendly' AND job LIKE 
'%smith' 
. SELECT PERSONID FROM INHABITANT WHERE NAME LIKE 'STRANGER'
. SELECT GOLD FROM INHABITANT WHERE NAME LIKE 'STRANGER'
. SELECT * FROM ITEM WHERE OWNER IS NULL
